spring:
  application:
    name: otel-spring-boot-starter-sandbox

management:
  server:
      port: 8081
  endpoints:
    web:
      exposure:
        include: health,info
  observations:
    annotations:
      # Enable observability annotations like @Timed, @Counted, @Gauge, etc.
      # https://docs.spring.io/spring-boot/reference/actuator/observability.html#actuator.observability.annotations
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
  otlp:
    # The metrics collected by micrometer-registry-otlp are sent to the otel-collector via HTTP
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 15s

otel:
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  metrics:
    # The metrics collected by OpenTelemetry Spring Boot starter are not sent to the otel-collector
    exporter: none
  traces:
    exporter: otlp
  logs:
    exporter: none
  resource:
    attributes:
      service.name: ${spring.application.name}
      service.version: 0.0.1-SNAPSHOT
      deployment.environment: local
