[versions]
kotlin = "1.9.25"
micrometerRegistryOtlp = "1.14.6"

[plugins]
springBoot = { id = "org.springframework.boot", version = "3.4.5" }
springDependencyManagement = { id = "io.spring.dependency-management", version = "1.1.7" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinPluginSpring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }

[libraries]
otelBom = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom", version = "2.15.0" }
micrometerRegistryOtlp = { module = "io.micrometer:micrometer-registry-otlp", version.ref = "micrometerRegistryOtlp" }
